---
- name: Preflight Check
  include: preflight.yml

- name: install/configures proxy nodes
  include_role:
    name: "kilip.squid"
  when: '"proxy" in group_names'

- name: install/configures mysql server
  include_role:
    name: mysql
  when: '"mysql" in group_names'

- name: install/configures k8s master and worker nodes
  include_role:
    name: cluster
  when: '"master" in group_names or "worker" in group_names'