- name: gather facts
  block:
    - name: gather service facts
      service_facts:
      register: s

    - name: set common facts
      set_fact:
        services: "{{ s.ansible_facts.services }}"
        host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: set user facts
      set_fact:
        olympus_user: "{{ lookup('env','USER') }}"
        olympus_homedir: "{{ lookup('env','HOME') }}"
      when: "olympus_user is not defined"
