apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFl3TXpjd09Ua3lOakFlRncweU1ERXdNall4TURVNE5EWmFGdzB6TURFd01qUXhNRFU0TkRaYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFl3TXpjd09Ua3lOakJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkNxWnBxS3BTTld5RXNtZk41Vjh4QVFaeWJFbVdjUVhzSlNEM2RlYlJXM00Kemdxc0RxQzVmYWxUVkUrVnZyWmwvN1VQQ05sdWJsaCtiekRlUVJFZEozV2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUVQMnZ0UHJud0hZCmxuTG9MTlRpMFovWU5BWkpCeWZ1VFM3THdHZE9WOVJDQWlFQXFvZ0VPYXVaWGdSOGd5amZGRmxMaUNmYWpJL1MKNXVSZCt1aXVLYXJLNGg4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.0.10.12:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 488e1fec314e798c6e43ddb66426b497
    username: admin
