- hosts: etcd
  become: true
  pre_tasks:
    - name: preflight check
      include_role:
        name: etcd
        tasks_from: preflight.yml
  tasks:
    - name: installs/configures etcd
      include_role:
        name: etcd

#- hosts: "k3s_nodes"
#  become: true
#  tasks:
#    - name: include preflight tasks
#      include_role: 
#        name: cluster
