- hosts: all
  name: cleanup k3s installation
  tasks:
    - name: "include cluster role"
      include_role:
        name: k3s
        tasks_from: "cleanup.yml"
      when: '"master" in group_names or "worker" in group_names'