---
version: "3"

tasks:
  default: task -l

  up:
    desc: bring containers up
    cmd: docker compose up -d {{.CLI_ARGS}}

  rm:
    desc: bring containers up
    cmd: docker compose rm {{.CLI_ARGS}}

  start:
    desc: bring containers up
    cmd: docker compose start
  
  restart:
    desc: bring containers restart
    cmd: docker compose restart {{.CLI_ARGS}}

  stop:
    desc: stop containers
    cmd: docker compose stop {{.CLI_ARGS}}

  logs:
    desc: show container logs
    cmd: docker compose logs -f --tail 10 {{.CLI_ARGS}}

  init:
    desc: configure containers
    cmds:
      - sudo mkdir -p vars/mosquitto
      - sudo chmod 0777 vars/mosquitto
      - task: secrets

  secrets:
    desc: initialize secrets configuration
    cmds:
      - mkdir -p ./secrets/
      - pass git pull
      - pass config/env.local > .env.local
      - pass config/cloudflare.ini > ./secrets/cloudflare.ini
      - task: .mosquitto

  .mosquitto:
    cmds:
      - pass config/mosquitto.conf > ./apps/mosquitto/mosquitto.conf
      - pass config/mosquitto.pwd > ./apps/mosquitto/mosquitto.pwd
      - chmod 0700 ./apps/mosquitto/mosquitto.pwd
      - docker compose exec mosquitto mosquitto_passwd -U /tmp/mosquitto.pwd || true
      - docker compose restart mosquitto || true
