netplan_config: |
  network:
    ethernets:
      enp0s3:
        dhcp4: true
        addresses:
          - 10.0.60.11/24
          - 10.0.60.21/24
          - 10.0.60.22/24
          - 10.0.60.23/24
          - 10.0.60.24/24
          - 10.0.60.25/24
        gateway4: 10.0.60.1
    version: 2