- name: start k3s
  systemd:
    name: "{{ service_name }}"
    daemon_reload: yes
    state: started
    enabled: yes
  register: ensure_k3s_started
  until: ensure_k3s_started is succeeded
  retries: "{{ play_hosts | length }}"
  delay: 5
  
- name: restart k3s
  systemd:
    name: "{{ service_name }}"
    daemon_reload: yes
    state: restarted
  register: ensure_k3s_started
  until: ensure_k3s_started is succeeded
  retries: "{{ play_hosts | length }}"
  delay: 5
