---
k3s_control_node_address: 10.0.60.11
k3s_datastore_endpoint: "https://10.0.60.11:2379,https://10.0.60.12:2379,https://10.0.60.13:2379"

molecule_is_test: false

k3s_write_kubeconfig_mode: "0644"
k3s_become_for_all: yes
k3s_release_version: stable
k3s_build_cluster: yes

k3s_datastore_cafile: "/etc/etcd/etcd-ca.crt"
k3s_datastore_certfile: "/etc/etcd/server.crt"
k3s_datastore_keyfile: "/etc/etcd/server.key"
k3s_control_node: true

k3s_no_traefik: yes
k3s_no_servicelb: yes
k3s_no_local_storage: yes
k3s_no_metrics_server: yes

systemd_dir: "/etc/systemd/system"

host_entries:
  - 10.0.60.11 hera-dev
  - 10.0.60.12 iris-dev
  - 10.0.60.13 mars-dev
  - 10.0.60.21 hera-dev