- name: copy cert files to etcd nodes
  copy:
    src: "{{ etcd_cert_local_temp_dir }}/{{ item.src }}"
    dest: "{{ etcd_conf_dir }}/{{ item.dest }}"
  with_items:
    - src: "ca.pem"
      dest: "etcd-ca.crt"
    - src: "{{ ansible_hostname }}.pem"
      dest: "server.crt"
    - src: "{{ ansible_hostname }}-key.pem"
      dest: "server.key"

- name: ensure access to server.key file
  file:
    path: "{{ etcd_conf_dir }}/server.key"
    mode: "0600"

- debug: var=etcd_initial_cluster

- name: generate etcd config
  template:
    src: "etcd.conf.j2"
    dest: "{{ etcd_conf_dir }}/etcd.conf"
  notify: restart etcd