- service_facts:
  register: facts
- set_fact:
    _etcd_service: "{{ facts.ansible_facts.services['etcd.service']['state'] | default('undefined') }}"
- set_fact:
    _etcd_handler: "{{ 'restart etcd' if _etcd_service == 'running' else 'start etcd' }}"

- name: configures etcd certs
  include: ca-cert.yml
  when: inventory_hostname == etcd_config_host

- name: ensure etcd installed
  include_role:
    name: "andrewrothstein.etcd"

- name: ensure etcd service installed
  template:
    src: "etcd.service.j2"
    dest: "/lib/systemd/system/etcd.service"
  notify: "{{ _etcd_handler }}"

- name: configures etcd
  include: config.yml