- debug: var=etcd_initial_cluster

- name: ensure etcd installed
  include_role:
    name: "andrewrothstein.etcd"

- name: configure etcd service
  include: service.yml

- name: configures etcd certs
  include: ca-cert.yml
  when: inventory_hostname == etcd_config_host

- name: configures etcd
  include: config.yml

- name: ensure etcd service enabled and started
  service:
    name: etcd
    enabled: yes
    state: started