- name: assert mysql service
  block:
    - service_facts:
      register: f
    - set_fact:
        s: '{{ f.ansible_facts.services["mysql.service"] }}'
    - assert:
        that: s.state == 'running'