---
- hosts: all
  tasks:
    - name: check proxy config
      set_fact:
        _proxy: "{{ lookup('env','APT_PROXY') }}"
        _mirror: "{{ lookup('env', 'APT_MIRROR') }}"
    - name: set apt proxy
      set_fact:
        apt_proxy: "{{ _proxy }}"
      when: _proxy|length > 0

    - name: set apt mirror
      set_fact:
        apt_mirror: "{{ _mirror }}"
      when: _mirror|length > 0

    - name: configure user
      set_fact:
        olympus_user: toni
        olympus_homedir: "/home/toni"

    - name: ensure group exists
      group:
        name: toni
        state: present

    - name: ensure user exists
      user:
        name: toni
        group: toni
        state: present
        groups: sudo
        append: yes

- name: import converge playbook
  vars:
    k8s_tools: no
    #apt_mirror: mirror.deace.id
    #apt_proxy: http://medusa.itstoni.com:3128
  import_playbook: "../../playbook-converge.yml"