---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - instance: olympus-node
    name: olympus-node
    image: "kilip/molecule-${MOLECULE_DIST:-ubuntu:20.04}"
    pre_build_image: true
    privileged: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - proxy
      #- mysql

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    MOLECULE_NO_LOG: false
    K3S_DOWNLOAD_URL: "${K3S_DOWNLOAD_URL:-https://github.com/rancher/k3s/releases/download}"
    ANSIBLE_VAULT_PASSWORD_FILE: "../../vault/password"
  inventory:
    links:
      #hosts: "./inventory/hosts.ini"
      group_vars: "./inventory/group_vars"
      host_vars: "./inventory/host_vars"
  playbooks:
    verify: "../../playbook-verify.yml"

lint: |
  ansible-lint

verifier:
  name: ansible