- name: include prerequisite role
  include_role:
    name: "./vendor/k3s-ansible/roles/prereq"

- name: downloading k3s
  include: download.yml

- include: control-node.yml
  when: k3s_control_node == inventory_hostname

- name: Store Master node-token
  block:
    - set_fact:
        cluster_token: "{{ hostvars[groups['master'][0]]['token'] }}"
    - set_fact:
        extra_server_args: "{{ extra_server_args + ['--token \"' ~ cluster_token ~ '\"']}}"

- include: k3s-master.yml
  when: "k3s_control_node !== inventory_hostname and 'master' in groups"

#- include: k3s-master.yml
#  when: "'master' in groups"