- name: get resolv.conf stat
  stat:
    path: "{{ resolv_conf_path }}"
  register: result

- name: "fix resolv.conf file"
  shell: "ln -sfn  /etc/resolv.conf"
  args:
    warn: no
  changed_when: false
  when: result.stat.exists

- name: "configures netplan"
  copy:
    content: "{{ netplan_config }}"
    dest: "/etc/netplan/50-cloud-init.yaml"
    backup: yes
  register: result
  when: netplan_config is defined

- name: "apply netplan changes"
  shell: "netplan apply --debug"
  when: result.changed

- name: "configures etcd certs"
  set_fact:
    k3s_datastore_cafile: "/etc/etcd/etcd-ca.crt"
    k3s_datastore_certfile: "/etc/etcd/server.crt"
    k3s_datastore_keyfile: "/etc/etcd/server.key"
  when: "'etcd' in groups"

- name: "set control node to true"
  set_fact:
    k3s_control_node: true
  when: "'master' in groups"

- name: "include k3s role"
  include_role:
    name: xanmanning.k3s
