- name: ensure required variables defined
  assert:
    that: "{{ item }} is defined"
    fail_msg: "'{{ item }}' value should be configured"
  with_items:
  - k3s_control_node_address
  - etcd_conf_dir
  - etcd_data_dir

- name: generate etcd cluster endpoints
  set_fact:
    _cluster_datastore_endpoints: "{{ _cluster_datastore_endpoints + ['https://' ~ hostvars[item]['ansible_default_ipv4']['address'] ~ ':2379' ] }} "
  with_items: "{{ groups['etcd'] }}"

- name: set datastore endpoints
  set_fact:
    k3s_datastore_endpoint: "{{ _cluster_datastore_endpoints|join(',') }}"