---
- service_facts:
  register: f

- set_fact:
    s: "{{ f.ansible_facts.services['k3s.service']['state'] }}"
  
- name: Copy K3s service file
  register: k3s_service
  template:
    src: "master.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755
  notify: "{{ 'restart k3s' if s == 'running' else 'start k3s' }}"
