- name: install/configures gpg
  include: packages/gpg.yml
  when: gpg

- name: install/configures git
  include: packages/git.yml
  when: git

- name: install/configures ohmyzsh
  include: packages/ohmyzsh.yml
  when: ohmyzsh

- name: install/configures kubernetes tools
  include: packages/k8s-tools.yml
  when: k8s_tools