---
_pwd: "{{ lookup('env', 'PWD') }}"
# k3s nodes setup
k3s_version: v1.18.3+k3s1
ansible_user: toni
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: |
  --tls-san k3s.itstoni.com --no-deploy traefik --no-deploy servicelb --no-deploy metrics-server --no-deploy local-storage --flannel-backend=host-gw --datastore-cafile=/etc/etcd/etcd-ca.crt --datastore-certfile=/etc/etcd/server.crt --datastore-keyfile=/etc/etcd/server.key  --datastore-endpoint="https://hera-dev:2379,https://iris-dev:2379,https://mars-dev:2379"

#ca_pem_file: "{{ playbook_dir }}/.secrets/cfssl/ca.pem"