hera ansible_host=10.0.10.11
iris ansible_host=10.0.10.12
mars ansible_host=10.0.10.13
eros ansible_host=10.0.10.14

[proxy]
eros

[master]
iris

[worker]
hera
mars

[k3s_nodes:children]
master
worker
