; list your available machine and ip address
hera ansible_host=10.0.10.11
iris ansible_host=10.0.10.12
mars ansible_host=10.0.10.13
eros ansible_host=10.0.10.14

; define your workstation here if any
[workstation]
; zeus

[mysql]
iris

; kubernetes master nodes
[master]
;hera
;iris
;mars

; kubernetes worker nodes
[nodes]

; etcd cluster nodes
[etcd]
master

[k3s_nodes:children]
master
nodes

[k3s_cluster:children]
master
nodes