etcd_config_host: "hera-dev"
etcd_conf_dir: "/etc/etcd"
etcd_data_dir: "/var/lib/etcd"

# k3s configuration
k3s_control_node: hera-dev
k3s_control_node_address: hostvars['hera-dev']['ansible_default_ipv4']['address']
molecule_testing: yes

extra_server_args:
  - --datastore-endpoint "mysql://olympus:olympus@tcp({{ k3s_control_node_address }}:3306)/olympus"
  - --no-deploy traefik
  - --no-deploy servicelb
  - --no-deploy metrics-server
  - --flannel-backend host-gw