name: Converge

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  converge:
    name: "Scenario: ${{ matrix.scenario }} (${{matrix.distro}})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - distro: ubuntu:20.04
          scenario: default
        - distro: ubuntu:20.04
          scenario: cluster
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          pip3 install -r requirements.txt
          ansible-galaxy install -r galaxy.yml
      - name: Run Molecule tests.
        run: |
          mkdir -p vault
          echo "$env:VAULT_PASSWORD" >> ./vault/password
          ls -l vault
          molecule test -s "${SCENARIO}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DIST: ${{ matrix.distro }}
          SCENARIO: ${{ matrix.scenario }}
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}
